# Generated by Django 5.1.4 on 2025-01-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activitymodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitymodel',
            name='user',
        ),
    ]
